spring:
  application:
    name: ci-cd-test
  cloud:
    stream:
      bindings:
        publishElementUpdate-out-0:
          destination:  ${powsybl-ws.rabbitmq.destination.prefix:}element.update
      output-bindings: publishElementUpdate-out-0
  main:
    allow-circular-references: true

powsybl-ws:
  database:
    name: ci-cd-test

server:
  max-http-header-size: 64000