name: CI-Front

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-frontend-app-generic.yml@54e99821dd0746fdb51d4e39a5ca2f029fe7fe33
    with:
      dockerImage: gridsuite/ci-cd-test:latest-front
      dockerUsername: gridsuiteci
      eventType: ci-cd-test_updated
      licensercPath: .github/config/.licenserc.yaml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
