name: CI-Front

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-frontend-app-generic.yml@dbfa51306075001d4f2191ab0a83bc5d959a93ea
    with:
      dockerImage: gridsuite/ci-cd-test
      dockerUsername: gridsuiteci
      eventType: ci-cd-test_updated
      licensercPath: .github/config/.licenserc.yaml
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
