name: CI-Docker

on:
  push:
    branches:
      - 'main'
      - 'use-docker-build-push-action'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@54e99821dd0746fdb51d4e39a5ca2f029fe7fe33
    with:
      dockerImage: gridsuite/ci-cd-test:latest-docker
      dockerUsername: gridsuiteci
      eventOrganizations: gridsuite
      eventType: java_updated
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
